---

resources:
  - name: repo
    type: git
    icon: github
    source:
      uri: https://github.com/bookwalker/ci-images.git
      branch: master

  - name: registry-gradle-chrome
    type: docker-image
    icon: docker
    source:
      repository: bookwalker/gradle-chrome
      username: ((registry-username))
      password: ((registry-password))

  - name: registry-node-chrome
    type: docker-image
    icon: docker
    source:
      repository: bookwalker/node-chrome
      username: ((registry-username))
      password: ((registry-password))

  - name: registry-ubuntu-ci
    type: docker-image
    icon: docker
    source:
      repository: bookwalker/ubuntu-ci
      username: ((registry-username))
      password: ((registry-password))

  - name: registry-ubuntu-ruby
    type: docker-image
    icon: docker
    source:
      repository: bookwalker/ubuntu-ruby
      username: ((registry-username))
      password: ((registry-password))




jobs:
  - name: build-gradle-image
    public: true
    plan:
      - get: repo
        trigger: true
      - put: registry-gradle-chrome
        timeout: 60m
        params:
          build: repo/
          dockerfile: repo/gradle-chrome/Dockerfile
          additional_tags: repo/gradle-chrome/version
        get_params:
          skip_download: true

  - name: build-node-image
    public: true
    plan:
      - get: repo
        trigger: true
      - put: registry-node-chrome
        timeout: 60m
        params:
          build: repo/
          dockerfile: repo/node-chrome/Dockerfile
          additional_tags: repo/node-chrome/version
        get_params:
          skip_download: true

  - name: build-ubuntu-ci-image
    public: true
    plan:
      - get: repo
        trigger: true
      - put: registry-ubuntu-ci
        timeout: 60m
        params:
          build: repo/
          dockerfile: repo/ubuntu-ci/Dockerfile
          additional_tags: repo/ubuntu-ci/version
        get_params:
          skip_download: true

  - name: build-ubuntu-ruby-image
    public: true
    plan:
      - get: repo
        trigger: true
      - put: registry-ubuntu-ruby
        timeout: 60m
        params:
          build: repo/
          dockerfile: repo/ubuntu-ruby/Dockerfile
          additional_tags: repo/ubuntu-ruby/version
        get_params:
          skip_download: true
